// GENERATED BY ClassesRelationIndexGenerator
enum RelationType { belongsTo,belongsToMany, hasOne, hasMany, manyToMany, isA }
class RelationMeta {
  final String fieldName;
  final String relatedType;
  final RelationType type;
  final String foreignKey;
   dynamic joinParentForeignKey;
   dynamic joinChildForeignKey;
  final bool cascadeOnDelete;
  final bool reuseIfExists;
  final bool updateIfExist;   //use upsert system
  final List<String> findBy;  //Needed for reuseIfExist BDD search
   RelationMeta({required this.fieldName,required this.relatedType,required this.type,required this.foreignKey,this.joinParentForeignKey, this.joinChildForeignKey, this.cascadeOnDelete= false,this.reuseIfExists=true, this.updateIfExist=true, this.findBy= const []});

   String toString(){
     return "RelationMeta(fieldName:$fieldName, relatedType:$relatedType, type:$type, foreignKey:$foreignKey,joinParentForeignKey:$joinParentForeignKey, joinChildForeignKey:$joinChildForeignKey,cascadeOnDelete:$cascadeOnDelete,reuseIfExists:$reuseIfExists,updateIfExist:$updateIfExist,findBy:${findBy.toString()})";
   }
}
final Map<String, List<RelationMeta>> ClassRelationsIndex = {
  'Address': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.belongsTo, foreignKey: 'person_id', findBy: const ['firstname','lastname']),
    RelationMeta(fieldName:'itinerary', relatedType:'Itinerary',type:RelationType.belongsTo, foreignKey: 'itinerary_id', findBy: const ['address_departure_id','address_arrival_id']),
  ],
  'Administrator': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.isA, foreignKey: 'person_id', findBy: const ['firstname','lastname','email']), //eq relation : is a
  ],
  'Assurance': [
    RelationMeta(fieldName:'photo', relatedType:'Photo',type:RelationType.hasOne, foreignKey: 'photo_id', findBy: const ['title','uri']),
    RelationMeta(fieldName:'vehicule', relatedType:'Vehicule',type:RelationType.belongsTo, foreignKey: 'vehicule_id', findBy: const ['immatriculation']),
  ],
  'AuthUser': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.belongsTo, foreignKey: 'person_id', findBy: const ['firstname','lastname','email']),
  ],
  'Command': [
    RelationMeta(fieldName:'user', relatedType:'User',type:RelationType.belongsTo, foreignKey: 'user_id', findBy: const ['firstname','lastname','email']),
  ],
  'Driver': [
    RelationMeta(fieldName:'notices', relatedType:'Notice',type:RelationType.hasMany, foreignKey: 'notices_id', findBy: const ['title','description']),
    RelationMeta(fieldName:'user', relatedType:'User',type:RelationType.isA, foreignKey: 'user_id', findBy: const ['firstname','lastname','email']),//eq relation : is a
    RelationMeta(fieldName:'drivingLicence', relatedType:'DrivingLicence',type:RelationType.hasOne, foreignKey: 'driving_licence_id', findBy: const ['identification_number']),
    RelationMeta(fieldName:'vehicule', relatedType:'Vehicule',type:RelationType.hasOne, foreignKey: 'vehicule_id', findBy: const ['immatriculation']),
  ],
  'DrivingLicence': [
    RelationMeta(fieldName:'driver', relatedType:'Driver',type:RelationType.belongsTo, foreignKey: 'driver_id', findBy: const ['firstname','lastname','email']),
    RelationMeta(fieldName:'photo', relatedType:'Photo',type:RelationType.hasOne, foreignKey: 'photo_id', findBy: const []),
  ],
  'Employee': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.isA, foreignKey: 'person_id', findBy: const ['firstname','lastname','email']),//eq relation : is a
  ],
  'Itinerary': [
    RelationMeta(fieldName:'addressDeparture', relatedType:'Address',type:RelationType.hasOne, foreignKey: 'addressDeparture_id', findBy: const ['address','post_code']),
    RelationMeta(fieldName:'addressArrival', relatedType:'Address',type:RelationType.hasOne, foreignKey: 'addressArrival_id', findBy: const ['address','post_code']),
    RelationMeta(fieldName:'travel', relatedType:'Travel',type:RelationType.belongsTo, foreignKey: 'travel_id', findBy: const ['driver_id','departure_time','arrival_time']),
  ],
  'Notice': [
    RelationMeta(fieldName:'driver', relatedType:'Driver',type:RelationType.belongsTo, foreignKey: 'driver_id', findBy: const ['firstname','lastname','email']),
  ],
  'Person': [
    RelationMeta(fieldName:'photo', relatedType:'Photo',type:RelationType.hasOne, foreignKey: 'photo_id', findBy: const ['title','uri'],cascadeOnDelete:false),
    RelationMeta(fieldName:'authUser', relatedType:'AuthUser',type:RelationType.hasOne, foreignKey: 'auth_user_id', findBy: const ['identifiant'],cascadeOnDelete:true),
    RelationMeta(fieldName:'user', relatedType:'User',type:RelationType.hasOne, foreignKey: 'user_id', findBy: const ['firstname','lastname','email'],cascadeOnDelete:false),
    RelationMeta(fieldName:'administrator', relatedType:'Administrator',type:RelationType.hasOne, foreignKey: 'administrator_id', findBy: const ['firstname','lastname','email'],cascadeOnDelete:false),
    RelationMeta(fieldName:'employee', relatedType:'Employee',type:RelationType.hasOne, foreignKey: 'employee_id', findBy: const ['firstname','lastname','email'],cascadeOnDelete:false),
  ],
  'Photo': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.belongsTo, foreignKey: 'person_id', findBy: const ['firstname','lastname','email']),
    RelationMeta(fieldName:'vehicule', relatedType:'Vehicule',type:RelationType.belongsTo, foreignKey: 'vehicule_id', findBy: const ['immatriculation']),
    RelationMeta(fieldName:'drivingLicence', relatedType:'DrivingLicence',type:RelationType.belongsTo, foreignKey: 'driving_licence_id', findBy: const ['identification_number']),
  ],
  'Travel': [
    RelationMeta(fieldName:'driver', relatedType:'Driver',type:RelationType.belongsTo, foreignKey: 'driver_id', findBy: const ['firstname','lastname','email']),
    RelationMeta(fieldName:'itinerary', relatedType:'Itinerary',type:RelationType.hasOne, foreignKey: 'itinerary_id', findBy: const ['address_departure_id','address_arrival_id']),
    RelationMeta(fieldName:'user', relatedType:'List',type:RelationType.hasMany, foreignKey: 'user_id', findBy: const ['firstname','lastname','email']),
  ],
  'User': [
    RelationMeta(fieldName:'person', relatedType:'Person',type:RelationType.isA, foreignKey: 'person_id', findBy: const ['firstname','lastname','email'],cascadeOnDelete:true),  //eq relation : is a
    RelationMeta(fieldName:'driver', relatedType:'Driver',type:RelationType.hasOne, foreignKey: 'driver_id', findBy: const ['firstname','lastname','email'],cascadeOnDelete:false),
    RelationMeta(fieldName:'commandList', relatedType:'Command',type:RelationType.hasMany, foreignKey: 'commandList_id', findBy: const ['reference'],cascadeOnDelete:false),
  ],
  'UserNoticeMtoM': [
    RelationMeta(fieldName:'notice', relatedType:'Notice',type:RelationType.belongsTo, foreignKey: 'notice_id', findBy: const ['title','description']),
    RelationMeta(fieldName:'user', relatedType:'User',type:RelationType.belongsTo, foreignKey: 'user_id', findBy: const ['firstname','lastname','email']),
  ],
  'Vehicule': [
    RelationMeta(fieldName:'photoList', relatedType:'Photo',type:RelationType.hasMany, foreignKey: 'photoList_id', findBy: const ['title','uri']),
    RelationMeta(fieldName:'driver', relatedType:'Driver',type:RelationType.belongsTo, foreignKey: 'driver_id', findBy: const ['firstname','lastname','email']),
    RelationMeta(fieldName:'assurance', relatedType:'Assurance',type:RelationType.hasOne, foreignKey: 'assurance_id', findBy: const ['identification_number']),
  ],
};
